# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C11
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	NoThread.exe \
	BasicThreads.exe \
	MoreBasicThreads.exe \
	UnresponsiveUI.exe \
	ResponsiveUI.exe \
	ThreadedExecutor.exe \
	PoolExecutor.exe \
	ConcurrentExecutor.exe \
	SynchronousExecutor.exe \
	YieldingTask.exe \
	SleepingTask.exe \
	SimplePriorities.exe \
	EvenChecker.$(OBJEXT) \
	EvenGenerator.exe \
	MutexEvenGenerator.exe \
	GuardedEvenGenerator.exe \
	TemporaryUnlocking.exe \
	TimedLocking.exe \
	OrnamentalGarden.exe \
	Interrupting.exe \
	Interrupting2.exe \
	Interrupting3.exe \
	Restaurant.exe \
	Bridge.exe \
	TestBoundedQueue.exe \
	SleepingBarber.exe \
	TestGuardedObjectTemplate.exe \
	DeadlockingDiningPhilosophers.exe \
	FixedDiningPhilosophers.exe

Microsoft:  \
	NoThread.exe \
	BasicThreads.exe \
	MoreBasicThreads.exe \
	UnresponsiveUI.exe \
	ResponsiveUI.exe \
	ThreadedExecutor.exe \
	PoolExecutor.exe \
	ConcurrentExecutor.exe \
	SynchronousExecutor.exe \
	YieldingTask.exe \
	SleepingTask.exe \
	SimplePriorities.exe \
	EvenChecker.$(OBJEXT) \
	EvenGenerator.exe \
	MutexEvenGenerator.exe \
	GuardedEvenGenerator.exe \
	TemporaryUnlocking.exe \
	TimedLocking.exe \
	OrnamentalGarden.exe \
	Interrupting.exe \
	Interrupting2.exe \
	Interrupting3.exe \
	Restaurant.exe \
	Bridge.exe \
	TestBoundedQueue.exe \
	SleepingBarber.exe \
	TestGuardedObjectTemplate.exe \
	DeadlockingDiningPhilosophers.exe \
	FixedDiningPhilosophers.exe

g++:  \
	NoThread.exe \
	BasicThreads.exe \
	MoreBasicThreads.exe \
	UnresponsiveUI.exe \
	ResponsiveUI.exe \
	ThreadedExecutor.exe \
	PoolExecutor.exe \
	ConcurrentExecutor.exe \
	SynchronousExecutor.exe \
	YieldingTask.exe \
	SleepingTask.exe \
	SimplePriorities.exe \
	EvenChecker.$(OBJEXT) \
	EvenGenerator.exe \
	MutexEvenGenerator.exe \
	GuardedEvenGenerator.exe \
	TemporaryUnlocking.exe \
	TimedLocking.exe \
	OrnamentalGarden.exe \
	Interrupting.exe \
	Interrupting2.exe \
	Interrupting3.exe \
	Restaurant.exe \
	Bridge.exe \
	TestBoundedQueue.exe \
	SleepingBarber.exe \
	TestGuardedObjectTemplate.exe \
	DeadlockingDiningPhilosophers.exe \
	FixedDiningPhilosophers.exe

edg:  \
	NoThread.exe \
	BasicThreads.exe \
	MoreBasicThreads.exe \
	UnresponsiveUI.exe \
	ResponsiveUI.exe \
	ThreadedExecutor.exe \
	PoolExecutor.exe \
	ConcurrentExecutor.exe \
	SynchronousExecutor.exe \
	YieldingTask.exe \
	SleepingTask.exe \
	SimplePriorities.exe \
	EvenChecker.$(OBJEXT) \
	EvenGenerator.exe \
	MutexEvenGenerator.exe \
	GuardedEvenGenerator.exe \
	TemporaryUnlocking.exe \
	TimedLocking.exe \
	OrnamentalGarden.exe \
	Interrupting.exe \
	Interrupting2.exe \
	Interrupting3.exe \
	Restaurant.exe \
	Bridge.exe \
	TestBoundedQueue.exe \
	SleepingBarber.exe \
	TestGuardedObjectTemplate.exe \
	DeadlockingDiningPhilosophers.exe \
	FixedDiningPhilosophers.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


NoThread.exe: NoThread.cpp

BasicThreads.exe: BasicThreads.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)BasicThreads.exe BasicThreads.$(OBJEXT) $(LIBLINK)Zthread

BasicThreads.$(OBJEXT): BasicThreads.cpp
MoreBasicThreads.exe: MoreBasicThreads.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MoreBasicThreads.exe MoreBasicThreads.$(OBJEXT) $(LIBLINK)Zthread

MoreBasicThreads.$(OBJEXT): MoreBasicThreads.cpp
UnresponsiveUI.exe: UnresponsiveUI.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)UnresponsiveUI.exe UnresponsiveUI.$(OBJEXT) $(LIBLINK)Zthread

UnresponsiveUI.$(OBJEXT): UnresponsiveUI.cpp
ResponsiveUI.exe: ResponsiveUI.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ResponsiveUI.exe ResponsiveUI.$(OBJEXT) $(LIBLINK)Zthread

ResponsiveUI.$(OBJEXT): ResponsiveUI.cpp
ThreadedExecutor.exe: ThreadedExecutor.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ThreadedExecutor.exe ThreadedExecutor.$(OBJEXT) $(LIBLINK)Zthread

ThreadedExecutor.$(OBJEXT): ThreadedExecutor.cpp
PoolExecutor.exe: PoolExecutor.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)PoolExecutor.exe PoolExecutor.$(OBJEXT) $(LIBLINK)Zthread

PoolExecutor.$(OBJEXT): PoolExecutor.cpp
ConcurrentExecutor.exe: ConcurrentExecutor.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)ConcurrentExecutor.exe ConcurrentExecutor.$(OBJEXT) $(LIBLINK)Zthread

ConcurrentExecutor.$(OBJEXT): ConcurrentExecutor.cpp
SynchronousExecutor.exe: SynchronousExecutor.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SynchronousExecutor.exe SynchronousExecutor.$(OBJEXT) $(LIBLINK)Zthread

SynchronousExecutor.$(OBJEXT): SynchronousExecutor.cpp
YieldingTask.exe: YieldingTask.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)YieldingTask.exe YieldingTask.$(OBJEXT) $(LIBLINK)Zthread

YieldingTask.$(OBJEXT): YieldingTask.cpp
SleepingTask.exe: SleepingTask.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SleepingTask.exe SleepingTask.$(OBJEXT) $(LIBLINK)Zthread

SleepingTask.$(OBJEXT): SleepingTask.cpp
SimplePriorities.exe: SimplePriorities.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SimplePriorities.exe SimplePriorities.$(OBJEXT) $(LIBLINK)Zthread

SimplePriorities.$(OBJEXT): SimplePriorities.cpp
EvenChecker.$(OBJEXT): EvenChecker.cpp

EvenGenerator.exe: EvenChecker.$(OBJEXT) EvenGenerator.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)EvenGenerator.exe EvenGenerator.$(OBJEXT) EvenChecker.$(OBJEXT) $(LIBLINK)Zthread

EvenGenerator.$(OBJEXT): EvenGenerator.cpp
MutexEvenGenerator.exe: EvenChecker.$(OBJEXT) MutexEvenGenerator.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)MutexEvenGenerator.exe MutexEvenGenerator.$(OBJEXT) EvenChecker.$(OBJEXT) $(LIBLINK)Zthread

MutexEvenGenerator.$(OBJEXT): MutexEvenGenerator.cpp
GuardedEvenGenerator.exe: EvenChecker.$(OBJEXT) GuardedEvenGenerator.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)GuardedEvenGenerator.exe GuardedEvenGenerator.$(OBJEXT) EvenChecker.$(OBJEXT) $(LIBLINK)Zthread

GuardedEvenGenerator.$(OBJEXT): GuardedEvenGenerator.cpp
TemporaryUnlocking.exe: TemporaryUnlocking.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TemporaryUnlocking.exe TemporaryUnlocking.$(OBJEXT) $(LIBLINK)Zthread

TemporaryUnlocking.$(OBJEXT): TemporaryUnlocking.cpp
TimedLocking.exe: TimedLocking.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TimedLocking.exe TimedLocking.$(OBJEXT) $(LIBLINK)Zthread

TimedLocking.$(OBJEXT): TimedLocking.cpp
OrnamentalGarden.exe: OrnamentalGarden.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)OrnamentalGarden.exe OrnamentalGarden.$(OBJEXT) $(LIBLINK)Zthread

OrnamentalGarden.$(OBJEXT): OrnamentalGarden.cpp
Interrupting.exe: Interrupting.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Interrupting.exe Interrupting.$(OBJEXT) $(LIBLINK)Zthread

Interrupting.$(OBJEXT): Interrupting.cpp
Interrupting2.exe: Interrupting2.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Interrupting2.exe Interrupting2.$(OBJEXT) $(LIBLINK)Zthread

Interrupting2.$(OBJEXT): Interrupting2.cpp
Interrupting3.exe: Interrupting3.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Interrupting3.exe Interrupting3.$(OBJEXT) $(LIBLINK)Zthread

Interrupting3.$(OBJEXT): Interrupting3.cpp
Restaurant.exe: Restaurant.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Restaurant.exe Restaurant.$(OBJEXT) $(LIBLINK)Zthread

Restaurant.$(OBJEXT): Restaurant.cpp
Bridge.exe: Bridge.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Bridge.exe Bridge.$(OBJEXT) $(LIBLINK)Zthread

Bridge.$(OBJEXT): Bridge.cpp
TestBoundedQueue.exe: TestBoundedQueue.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TestBoundedQueue.exe TestBoundedQueue.$(OBJEXT) $(LIBLINK)Zthread

TestBoundedQueue.$(OBJEXT): TestBoundedQueue.cpp
SleepingBarber.exe: SleepingBarber.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)SleepingBarber.exe SleepingBarber.$(OBJEXT) $(LIBLINK)Zthread

SleepingBarber.$(OBJEXT): SleepingBarber.cpp
TestGuardedObjectTemplate.exe: TestGuardedObjectTemplate.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)TestGuardedObjectTemplate.exe TestGuardedObjectTemplate.$(OBJEXT) $(LIBLINK)Zthread

TestGuardedObjectTemplate.$(OBJEXT): TestGuardedObjectTemplate.cpp
DeadlockingDiningPhilosophers.exe: DeadlockingDiningPhilosophers.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)DeadlockingDiningPhilosophers.exe DeadlockingDiningPhilosophers.$(OBJEXT) $(LIBLINK)Zthread

DeadlockingDiningPhilosophers.$(OBJEXT): DeadlockingDiningPhilosophers.cpp
FixedDiningPhilosophers.exe: FixedDiningPhilosophers.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)FixedDiningPhilosophers.exe FixedDiningPhilosophers.$(OBJEXT) $(LIBLINK)Zthread

FixedDiningPhilosophers.$(OBJEXT): FixedDiningPhilosophers.cpp
