# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C08
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	CheckedCast.exe \
	CheckedCast2.exe \
	TypeInfo.exe \
	RTTIandNesting.exe \
	IntermediateCast.exe \
	VoidRTTI.exe \
	ConstructorOrder.exe \
	RTTIandMultipleInheritance.exe \
	Recycle.exe \
	Recycle2.exe

Microsoft:  \
	CheckedCast.exe \
	CheckedCast2.exe \
	TypeInfo.exe \
	RTTIandNesting.exe \
	IntermediateCast.exe \
	VoidRTTI.exe \
	ConstructorOrder.exe \
	RTTIandMultipleInheritance.exe \
	Recycle.exe \
	Recycle2.exe

g++:  \
	CheckedCast.exe \
	CheckedCast2.exe \
	TypeInfo.exe \
	RTTIandNesting.exe \
	IntermediateCast.exe \
	VoidRTTI.exe \
	ConstructorOrder.exe \
	RTTIandMultipleInheritance.exe \
	Recycle.exe \
	Recycle2.exe

edg:  \
	CheckedCast.exe \
	CheckedCast2.exe \
	TypeInfo.exe \
	RTTIandNesting.exe \
	IntermediateCast.exe \
	VoidRTTI.exe \
	ConstructorOrder.exe \
	RTTIandMultipleInheritance.exe \
	Recycle.exe \
	Recycle2.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


CheckedCast.exe: CheckedCast.cpp

CheckedCast2.exe: CheckedCast2.cpp

TypeInfo.exe: TypeInfo.cpp

RTTIandNesting.exe: RTTIandNesting.cpp

IntermediateCast.exe: IntermediateCast.cpp

VoidRTTI.exe: VoidRTTI.cpp

ConstructorOrder.exe: ConstructorOrder.cpp

RTTIandMultipleInheritance.exe: RTTIandMultipleInheritance.cpp

Recycle.exe: Recycle.cpp

Recycle2.exe: Recycle2.cpp

