# From "Thinking in C++, 2nd Edition, Volume 2" 
# by Bruce Eckel & Chuck Allison
# Available at http://www.BruceEckel.com
# (c)2003 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\C05
# Invoke with: make compiler-name
# or: make clean

ifneq ($(MAKECMDGOALS),clean)
include ../$(MAKECMDGOALS).mac
endif

.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(CPPFLAGS) $(OFLAGS) $<


Borland:  \
	FuncDef.exe \
	TempTemp.exe \
	TempTemp2.exe \
	PrintSeq.exe \
	UsingTypename.exe \
	DotTemplate.exe \
	MemberClass.exe \
	StringConvTest.exe \
	ImplicitCast.exe \
	ArraySize.exe \
	MinTest.exe \
	TemplateFunctionAddress.exe \
	StrTolower.$(OBJEXT) \
	Tolower.exe \
	ToLower2.exe \
	ApplyGromit.exe \
	PartialOrder.exe \
	MinTest2.exe \
	PartialOrder2.exe \
	Sorted.exe \
	DelayedInstantiation.exe \
	NobloatTest.exe \
	FriendScope.exe \
	FriendScope2.exe \
	Box1.exe \
	Box2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	Factorial.exe \
	Fibonacci.exe \
	Power.exe \
	Accumulate.exe \
	Max.exe \
	Conditionals.exe \
	StaticAssert.exe \
	ExplicitInstantiation.exe

Microsoft:  \
	UrandTest.exe \
	FuncDef.exe \
	TempTemp.exe \
	TempTemp2.exe \
	TypenamedID.exe \
	UsingTypename.exe \
	DotTemplate.exe \
	MemberClass.exe \
	StringConvTest.exe \
	ImplicitCast.exe \
	ArraySize.exe \
	MinTest.exe \
	TemplateFunctionAddress.exe \
	StrTolower.$(OBJEXT) \
	Tolower.exe \
	ToLower2.exe \
	ApplyGromit.exe \
	PartialOrder.exe \
	MinTest2.exe \
	PartialOrder2.exe \
	Sorted.exe \
	DelayedInstantiation.exe \
	NobloatTest.exe \
	Lookup2.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	Box1.exe \
	Box2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	Factorial.exe \
	Fibonacci.exe \
	Power.exe \
	Accumulate.exe \
	Max.exe \
	Conditionals.exe \
	StaticAssert.exe

g++:  \
	UrandTest.exe \
	FuncDef.exe \
	TempTemp.exe \
	TempTemp2.exe \
	TempTemp3.exe \
	TempTemp4.exe \
	TypenamedID.exe \
	PrintSeq.exe \
	UsingTypename.exe \
	DotTemplate.exe \
	MemberClass.exe \
	StringConvTest.exe \
	ImplicitCast.exe \
	ArraySize.exe \
	MinTest.exe \
	TemplateFunctionAddress.exe \
	StrTolower.$(OBJEXT) \
	Tolower.exe \
	ToLower2.exe \
	ApplyGromit.exe \
	PartialOrder.exe \
	MinTest2.exe \
	PartialOrder2.exe \
	Sorted.exe \
	DelayedInstantiation.exe \
	NobloatTest.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	Box1.exe \
	Box2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	Factorial.exe \
	Fibonacci.exe \
	Power.exe \
	Accumulate.exe \
	Max.exe \
	Conditionals.exe \
	ExplicitInstantiation.exe

edg:  \
	UrandTest.exe \
	FuncDef.exe \
	TempTemp.exe \
	TempTemp2.exe \
	TempTemp3.exe \
	TempTemp4.exe \
	TypenamedID.exe \
	PrintSeq.exe \
	UsingTypename.exe \
	DotTemplate.exe \
	MemberClass.exe \
	StringConvTest.exe \
	ImplicitCast.exe \
	ArraySize.exe \
	MinTest.exe \
	TemplateFunctionAddress.exe \
	StrTolower.$(OBJEXT) \
	Tolower.exe \
	ToLower2.exe \
	ApplyGromit.exe \
	PartialOrder.exe \
	MinTest2.exe \
	PartialOrder2.exe \
	Sorted.exe \
	DelayedInstantiation.exe \
	NobloatTest.exe \
	Lookup2.exe \
	FriendScope.exe \
	FriendScope2.exe \
	FriendScope3.exe \
	Box1.exe \
	Box2.exe \
	PoohCorner.exe \
	PoohCorner2.exe \
	CountedClass.exe \
	CountedClass2.exe \
	CountedClass3.exe \
	Factorial.exe \
	Fibonacci.exe \
	Power.exe \
	Accumulate.exe \
	Max.exe \
	Conditionals.exe \
	StaticAssert.exe \
	ExplicitInstantiation.exe

clean:
ifeq ($(notdir $(SHELL)),COMMAND.COM)
	del *.obj
	del *.exe
	del *.tds
	del *.o
else
	rm -f *.o *.obj *.exe *.tds
endif


UrandTest.exe: UrandTest.cpp

FuncDef.exe: FuncDef.cpp

TempTemp.exe: TempTemp.cpp

TempTemp2.exe: TempTemp2.cpp

TempTemp3.exe: TempTemp3.cpp

TempTemp4.exe: TempTemp4.cpp

TypenamedID.exe: TypenamedID.cpp

PrintSeq.exe: PrintSeq.cpp

UsingTypename.exe: UsingTypename.cpp

DotTemplate.exe: DotTemplate.cpp

MemberClass.exe: MemberClass.cpp

StringConvTest.exe: StringConvTest.cpp

ImplicitCast.exe: ImplicitCast.cpp

ArraySize.exe: ArraySize.cpp

MinTest.exe: MinTest.cpp

TemplateFunctionAddress.exe: TemplateFunctionAddress.cpp

StrTolower.$(OBJEXT): StrTolower.cpp

Tolower.exe: StrTolower.$(OBJEXT) Tolower.$(OBJEXT)
	$(CPP) $(CPPFLAGS) $(EXEFLAG)Tolower.exe Tolower.$(OBJEXT) StrTolower.$(OBJEXT)

Tolower.$(OBJEXT): Tolower.cpp
ToLower2.exe: ToLower2.cpp

ApplyGromit.exe: ApplyGromit.cpp

PartialOrder.exe: PartialOrder.cpp

MinTest2.exe: MinTest2.cpp

PartialOrder2.exe: PartialOrder2.cpp

Sorted.exe: Sorted.cpp

DelayedInstantiation.exe: DelayedInstantiation.cpp

NobloatTest.exe: NobloatTest.cpp

Lookup2.exe: Lookup2.cpp

FriendScope.exe: FriendScope.cpp

FriendScope2.exe: FriendScope2.cpp

FriendScope3.exe: FriendScope3.cpp

Box1.exe: Box1.cpp

Box2.exe: Box2.cpp

PoohCorner.exe: PoohCorner.cpp

PoohCorner2.exe: PoohCorner2.cpp

CountedClass.exe: CountedClass.cpp

CountedClass2.exe: CountedClass2.cpp

CountedClass3.exe: CountedClass3.cpp

Factorial.exe: Factorial.cpp

Fibonacci.exe: Fibonacci.cpp

Power.exe: Power.cpp

Accumulate.exe: Accumulate.cpp

Max.exe: Max.cpp

Conditionals.exe: Conditionals.cpp

StaticAssert.exe: StaticAssert.cpp

ExplicitInstantiation.exe: ExplicitInstantiation.cpp

